name: Solar Theme
url: http://github.kuaikuaicodingme.com/blog
description: A stylish blog using the Solarized color palette
baseurl: ''
permalink: /:year/:month/:day/:title/
paginate: 10
highlighter: pygments

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
